"""insert fake events

Revision ID: 310505994e5e
Revises: d0a445b97d4c
Create Date: 2023-09-30 16:50:04.636774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310505994e5e'
down_revision: Union[str, None] = 'd0a445b97d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        INSERT INTO
            events(title,start_event,end_event)
        VALUES
        ('Python Flask coding visual studio', '2021-07-03 16:00:00', '2021-07-04 03:00:00'),
        ('PHP coding Notepad++', '2021-07-08 03:17:15', '2021-07-10 04:00:00'),
        ('Basketball', '2021-07-05 00:00:00', '2021-07-05 14:30:00'),
        ('Birthday Party', '2021-07-12 00:00:00', '2021-07-13 00:00:00');
    """)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
