"""add table events

Revision ID: 4d6f976bcab7
Revises: e6b6311af989
Create Date: 2023-10-07 16:29:44.140573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6f976bcab7'
down_revision: Union[str, None] = 'e6b6311af989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
            sa.Column('id', sa.Integer(), primary_key=True),
            sa.Column('title', sa.String(), nullable=False),
            sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id')),
            sa.Column('procedure_id', sa.Integer(), sa.ForeignKey('procedures.id')),
            sa.Column('start_event', sa.DateTime()),
            sa.Column('end_event', sa.DateTime()),
        )

def downgrade() -> None:
    op.drop_table('events')
