"""create clients table

Revision ID: d0a445b97d4c
Revises: 
Create Date: 2023-09-30 16:42:49.603271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a445b97d4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
        sa.Column('id', sa.Integer, nullable=False),
        sa.Column('name', sa.VARCHAR(256), nullable=False),
        sa.Column('document', sa.VARCHAR(14), nullable=True),
        sa.Column('phone',sa.VARCHAR(15), nullable=False),
        sa.Column('dt_nasc', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
